#pragma once


namespace NMaxestFramework { namespace NSystem
{
	enum class EKey
	{
		Escape = 41, // SDL_SCANCODE_ESCAPE,
		Space = 44, // SDL_SCANCODE_SPACE,
		Return = 40, // SDL_SCANCODE_RETURN,
		Tab = 43, // SDL_SCANCODE_TAB,
		LShift = 225, // SDL_SCANCODE_LSHIFT,
		LCtrl = 224, // SDL_SCANCODE_LCTRL,
		LAlt = 226, // SDL_SCANCODE_LALT,
		RShift = 229, // SDL_SCANCODE_RSHIFT,
		RCtrl = 228, // SDL_SCANCODE_RCTRL,
		RAlt = 230, // SDL_SCANCODE_RALT,
		Left = 80, // SDL_SCANCODE_LEFT,
		Right = 79, // SDL_SCANCODE_RIGHT,
		Up = 82, // SDL_SCANCODE_UP,
		Down = 81, // SDL_SCANCODE_DOWN,
		Insert = 73, // SDL_SCANCODE_INSERT,
		Delete = 76, // SDL_SCANCODE_DELETE,
		Home = 74, // SDL_SCANCODE_HOME,
		End = 77, // SDL_SCANCODE_END,
		PageUp = 75, // SDL_SCANCODE_PAGEUP,
		PageDown = 78, // SDL_SCANCODE_PAGEDOWN,
		_0 = 39, // SDL_SCANCODE_0,
		_1 = 30, // SDL_SCANCODE_1,
		_2 = 31, // SDL_SCANCODE_2,
		_3 = 32, // SDL_SCANCODE_3,
		_4 = 33, // SDL_SCANCODE_4,
		_5 = 34, // SDL_SCANCODE_5,
		_6 = 35, // SDL_SCANCODE_6,
		_7 = 36, // SDL_SCANCODE_7,
		_8 = 37, // SDL_SCANCODE_8,
		_9 = 38, // SDL_SCANCODE_9,
		A = 4, // SDL_SCANCODE_A,
		B = 5, // SDL_SCANCODE_B,
		C = 6, // SDL_SCANCODE_C,
		D = 7, // SDL_SCANCODE_D,
		E = 8, // SDL_SCANCODE_E,
		F = 9, // SDL_SCANCODE_F,
		G = 10, // SDL_SCANCODE_G,
		H = 11, // SDL_SCANCODE_H,
		I = 12, // SDL_SCANCODE_I,
		J = 13, // SDL_SCANCODE_J,
		K = 14, // SDL_SCANCODE_K,
		L = 15, // SDL_SCANCODE_L,
		M = 16, // SDL_SCANCODE_M,
		N = 17, // SDL_SCANCODE_N,
		O = 18, // SDL_SCANCODE_O,
		P = 19, // SDL_SCANCODE_P,
		Q = 20, // SDL_SCANCODE_Q,
		R = 21, // SDL_SCANCODE_R,
		S = 22, // SDL_SCANCODE_S,
		T = 23, // SDL_SCANCODE_T,
		U = 24, // SDL_SCANCODE_U,
		V = 25, // SDL_SCANCODE_V,
		W = 26, // SDL_SCANCODE_W,
		X = 27, // SDL_SCANCODE_X,
		Y = 28, // SDL_SCANCODE_Y,
		Z = 29, // SDL_SCANCODE_Z,
		F1 = 58, // SDL_SCANCODE_F1,
		F2 = 59, // SDL_SCANCODE_F2,
		F3 = 60, // SDL_SCANCODE_F3,
		F4 = 61, // SDL_SCANCODE_F4,
		F5 = 62, // SDL_SCANCODE_F5,
		F6 = 63, // SDL_SCANCODE_F6,
		F7 = 64, // SDL_SCANCODE_F7,
		F8 = 65, // SDL_SCANCODE_F8,
		F9 = 66, // SDL_SCANCODE_F9,
		F10 = 67, // SDL_SCANCODE_F10,
		F11 = 68, // SDL_SCANCODE_F11,
		F12 = 69, // SDL_SCANCODE_F12,
	};
} }
